version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    #container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  db:
    image: postgres
    #container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data      
  adminer:
    image: adminer
    #container_name: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8080:8080
  apigateway:
    #image: bezlla/apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - 7052:7052
  usersapi:
    #image: bezlla/usersapi
    build:
      context: .
      dockerfile: User/Dockerfile
    ports:
      - 7205:7205
    depends_on:
      - db
  messagesapi:
    #image: bezlla/messagesapi
    build:
      context: .
      dockerfile: Message/Dockerfile
    ports:
      - 7191:7191
    depends_on:
      - db

volumes:
  rabbitmq_data:
  postgres_data: